-- AlterTable
ALTER TABLE `news_list` MODIFY `title` VARCHAR(600) NOT NULL,
    MODIFY `img1` VARCHAR(600) NOT NULL,
    MODIFY `img2` VARCHAR(600) NOT NULL,
    MODIFY `img3` VARCHAR(600) NOT NULL,
    MODIFY `img4` VARCHAR(600) NOT NULL,
    MODIFY `keywords` VARCHAR(600) NOT NULL,
    MODIFY `type` VARCHAR(600) NOT NULL;

-- AlterTable
ALTER TABLE `socials` MODIFY `facebook` VARCHAR(600) NOT NULL,
    MODIFY `linkedin` VARCHAR(600) NOT NULL,
    MODIFY `twiter` VARCHAR(600) NOT NULL,
    MODIFY `youtube` VARCHAR(600) NOT NULL,
    MODIFY `about` VARCHAR(600) NOT NULL,
    MODIFY `address` VARCHAR(600) NOT NULL;
